name: 'sustain_3p'
version: '1.0.0'
config-version: 2
profile: 'sustain-nonprod-snowflake'

require-dbt-version: [">=0.18.0", "<0.20.0"]

vars:
  ad_reporting:
    ad_reporting__pinterest_enabled: false
    ad_reporting__microsoft_ads_enabled: true
    ad_reporting__linkedin_ads_enabled: true
    ad_reporting__google_ads_enabled: true
    ad_reporting__twitter_ads_enabled: false
    ad_reporting__facebook_ads_enabled: false

  # Marketing
  hubspot:
    hubspot_marketing_enabled: true                        # Disables all marketing models
    hubspot_contact_enabled: false                          # Disables the contact models
    hubspot_contact_list_enabled:  false                    # Disables contact list models
    hubspot_contact_list_member_enabled: false              # Disables contact list member models
    hubspot_contact_property_enabled: false                 # Disables the contact property models
    hubspot_email_event_enabled: false                      # Disables all email_event models and functionality
    hubspot_email_event_bounce_enabled: false
    hubspot_email_event_click_enabled: false
    hubspot_email_event_deferred_enabled: false
    hubspot_email_event_delivered_enabled: false
    hubspot_email_event_dropped_enabled: false
    hubspot_email_event_forward_enabled: false
    hubspot_email_event_opens_enabled: false
    hubspot_email_event_print_enabled: false
    hubspot_email_event_sent_enabled: false
    hubspot_email_event_spam_report: false
    hubspot_email_event_status_change_enabled: false

    # Sales

    hubspot_sales_enabled: true                            # Disables all sales models
    hubspot_company_enabled: false
    hubspot_deal_enabled: false
    hubspot_engagement_enabled: false                       # Disables all engagement models and functionality
    hubspot_engagement_contact_enabled: false
    hubspot_engagement_company_enabled: false
    hubspot_engagement_deal_enabled: false
    hubspot_engagement_calls_enabled: false
    hubspot_engagement_emails_enabled: false
    hubspot_engagement_meetings_enabled: false
    hubspot_engagement_notes_enabled: false
    hubspot_engagement_tasks_enabled: false

models:
  ad_reporting:
    ad_reporting:
      +materialized: view

    pinterest:
      enabled: false
    pinterest_source:
      enabled: false

    microsoft_ads:
      enabled: true
    microsoft_ads_source:
      enabled: true

    linkedin:
      enabled: true
    linkedin_source:
      enabled: true

    twitter_ads:
      enabled: false
    twitter_ads_source:
      enabled: false

    facebook_ads:
      enabled: true
    facebook_ads_source:
      enabled: true
    facebook_ads_creative_history:
      enabled: false

    google_ads:
      enabled: true
    google_ads_source:
      enabled: true